<?php
if ( ! defined( 'WPINC' ) ) {
	die;
}

class Epsilon_Icons {
	public static function icons() {
		return apply_filters( 'epsilon_icon_pack', array(
			'fa fa-500px'                  => array( 'label' => '500px', 'group' => 'general' ),
			'fa fa-adjust'                 => array( 'label' => 'Adjust', 'group' => 'general' ),
			'fa fa-adn'                    => array( 'label' => 'Adn', 'group' => 'general' ),
			'fa fa-align-center'           => array( 'label' => 'Align Center', 'group' => 'general' ),
			'fa fa-align-justify'          => array( 'label' => 'Align Justify', 'group' => 'general' ),
			'fa fa-align-left'             => array( 'label' => 'Align Left', 'group' => 'general' ),
			'fa fa-align-right'            => array( 'label' => 'Align Right', 'group' => 'general' ),
			'fa fa-amazon'                 => array( 'label' => 'Amazon', 'group' => 'general' ),
			'fa fa-ambulance'              => array( 'label' => 'Ambulance', 'group' => 'general' ),
			'fa fa-anchor'                 => array( 'label' => 'Anchor', 'group' => 'general' ),
			'fa fa-android'                => array( 'label' => 'Android', 'group' => 'general' ),
			'fa fa-angellist'              => array( 'label' => 'Angellist', 'group' => 'general' ),
			'fa fa-angle-double-down'      => array( 'label' => 'Angle Double Down', 'group' => 'general' ),
			'fa fa-angle-double-left'      => array( 'label' => 'Angle Double Left', 'group' => 'general' ),
			'fa fa-angle-double-right'     => array( 'label' => 'Angle Double Right', 'group' => 'general' ),
			'fa fa-angle-double-up'        => array( 'label' => 'Angle Double Up', 'group' => 'general' ),
			'fa fa-angle-down'             => array( 'label' => 'Angle Down', 'group' => 'general' ),
			'fa fa-angle-left'             => array( 'label' => 'Angle Left', 'group' => 'general' ),
			'fa fa-angle-right'            => array( 'label' => 'Angle Right', 'group' => 'general' ),
			'fa fa-angle-up'               => array( 'label' => 'Angle Up', 'group' => 'general' ),
			'fa fa-apple'                  => array( 'label' => 'Apple', 'group' => 'general' ),
			'fa fa-archive'                => array( 'label' => 'Archive', 'group' => 'general' ),
			'fa fa-area-chart'             => array( 'label' => 'Area Chart', 'group' => 'general' ),
			'fa fa-arrow-circle-down'      => array( 'label' => 'Arrow Circle Down', 'group' => 'general' ),
			'fa fa-arrow-circle-left'      => array( 'label' => 'Arrow Circle Left', 'group' => 'general' ),
			'fa fa-arrow-circle-o-down'    => array( 'label' => 'Arrow Circle O Down', 'group' => 'general' ),
			'fa fa-arrow-circle-o-left'    => array( 'label' => 'Arrow Circle O Left', 'group' => 'general' ),
			'fa fa-arrow-circle-o-right'   => array( 'label' => 'Arrow Circle O Right', 'group' => 'general' ),
			'fa fa-arrow-circle-o-up'      => array( 'label' => 'Arrow Circle O Up', 'group' => 'general' ),
			'fa fa-arrow-circle-right'     => array( 'label' => 'Arrow Circle Right', 'group' => 'general' ),
			'fa fa-arrow-circle-up'        => array( 'label' => 'Arrow Circle Up', 'group' => 'general' ),
			'fa fa-arrow-down'             => array( 'label' => 'Arrow Down', 'group' => 'general' ),
			'fa fa-arrow-left'             => array( 'label' => 'Arrow Left', 'group' => 'general' ),
			'fa fa-arrow-right'            => array( 'label' => 'Arrow Right', 'group' => 'general' ),
			'fa fa-arrow-up'               => array( 'label' => 'Arrow Up', 'group' => 'general' ),
			'fa fa-arrows'                 => array( 'label' => 'Arrows', 'group' => 'general' ),
			'fa fa-arrows-alt'             => array( 'label' => 'Arrows Alt', 'group' => 'general' ),
			'fa fa-arrows-h'               => array( 'label' => 'Arrows H', 'group' => 'general' ),
			'fa fa-arrows-v'               => array( 'label' => 'Arrows V', 'group' => 'general' ),
			'fa fa-asterisk'               => array( 'label' => 'Asterisk', 'group' => 'general' ),
			'fa fa-at'                     => array( 'label' => 'At', 'group' => 'general' ),
			'fa fa-automobile'             => array( 'label' => 'Automobile', 'group' => 'general' ),
			'fa fa-backward'               => array( 'label' => 'Backward', 'group' => 'general' ),
			'fa fa-balance-scale'          => array( 'label' => 'Balance Scale', 'group' => 'general' ),
			'fa fa-ban'                    => array( 'label' => 'Ban', 'group' => 'general' ),
			'fa fa-bank'                   => array( 'label' => 'Bank', 'group' => 'general' ),
			'fa fa-bar-chart'              => array( 'label' => 'Bar Chart', 'group' => 'general' ),
			'fa fa-bar-chart-o'            => array( 'label' => 'Bar Chart O', 'group' => 'general' ),
			'fa fa-barcode'                => array( 'label' => 'Barcode', 'group' => 'general' ),
			'fa fa-bars'                   => array( 'label' => 'Bars', 'group' => 'general' ),
			'fa fa-battery-0'              => array( 'label' => 'Battery 0', 'group' => 'general' ),
			'fa fa-battery-1'              => array( 'label' => 'Battery 1', 'group' => 'general' ),
			'fa fa-battery-2'              => array( 'label' => 'Battery 2', 'group' => 'general' ),
			'fa fa-battery-3'              => array( 'label' => 'Battery 3', 'group' => 'general' ),
			'fa fa-battery-4'              => array( 'label' => 'Battery 4', 'group' => 'general' ),
			'fa fa-battery-empty'          => array( 'label' => 'Battery Empty', 'group' => 'general' ),
			'fa fa-battery-full'           => array( 'label' => 'Battery Full', 'group' => 'general' ),
			'fa fa-battery-half'           => array( 'label' => 'Battery Half', 'group' => 'general' ),
			'fa fa-battery-quarter'        => array( 'label' => 'Battery Quarter', 'group' => 'general' ),
			'fa fa-battery-three-quarters' => array( 'label' => 'Battery Three Quarters', 'group' => 'general' ),
			'fa fa-bed'                    => array( 'label' => 'Bed', 'group' => 'general' ),
			'fa fa-beer'                   => array( 'label' => 'Beer', 'group' => 'general' ),
			'fa fa-behance'                => array( 'label' => 'Behance', 'group' => 'general' ),
			'fa fa-behance-square'         => array( 'label' => 'Behance Square', 'group' => 'general' ),
			'fa fa-bell'                   => array( 'label' => 'Bell', 'group' => 'general' ),
			'fa fa-bell-o'                 => array( 'label' => 'Bell O', 'group' => 'general' ),
			'fa fa-bell-slash'             => array( 'label' => 'Bell Slash', 'group' => 'general' ),
			'fa fa-bell-slash-o'           => array( 'label' => 'Bell Slash O', 'group' => 'general' ),
			'fa fa-bicycle'                => array( 'label' => 'Bicycle', 'group' => 'general' ),
			'fa fa-binoculars'             => array( 'label' => 'Binoculars', 'group' => 'general' ),
			'fa fa-birthday-cake'          => array( 'label' => 'Birthday Cake', 'group' => 'general' ),
			'fa fa-bitbucket'              => array( 'label' => 'Bitbucket', 'group' => 'general' ),
			'fa fa-bitbucket-square'       => array( 'label' => 'Bitbucket Square', 'group' => 'general' ),
			'fa fa-bitcoin'                => array( 'label' => 'Bitcoin', 'group' => 'general' ),
			'fa fa-black-tie'              => array( 'label' => 'Black Tie', 'group' => 'general' ),
			'fa fa-bluetooth'              => array( 'label' => 'Bluetooth', 'group' => 'general' ),
			'fa fa-bluetooth-b'            => array( 'label' => 'Bluetooth B', 'group' => 'general' ),
			'fa fa-bold'                   => array( 'label' => 'Bold', 'group' => 'general' ),
			'fa fa-bolt'                   => array( 'label' => 'Bolt', 'group' => 'general' ),
			'fa fa-bomb'                   => array( 'label' => 'Bomb', 'group' => 'general' ),
			'fa fa-book'                   => array( 'label' => 'Book', 'group' => 'general' ),
			'fa fa-bookmark'               => array( 'label' => 'Bookmark', 'group' => 'general' ),
			'fa fa-bookmark-o'             => array( 'label' => 'Bookmark O', 'group' => 'general' ),
			'fa fa-briefcase'              => array( 'label' => 'Briefcase', 'group' => 'general' ),
			'fa fa-btc'                    => array( 'label' => 'Btc', 'group' => 'general' ),
			'fa fa-bug'                    => array( 'label' => 'Bug', 'group' => 'general' ),
			'fa fa-building'               => array( 'label' => 'Building', 'group' => 'general' ),
			'fa fa-building-o'             => array( 'label' => 'Building O', 'group' => 'general' ),
			'fa fa-bullhorn'               => array( 'label' => 'Bullhorn', 'group' => 'general' ),
			'fa fa-bullseye'               => array( 'label' => 'Bullseye', 'group' => 'general' ),
			'fa fa-bus'                    => array( 'label' => 'Bus', 'group' => 'general' ),
			'fa fa-buysellads'             => array( 'label' => 'Buysellads', 'group' => 'general' ),
			'fa fa-cab'                    => array( 'label' => 'Cab', 'group' => 'general' ),
			'fa fa-calculator'             => array( 'label' => 'Calculator', 'group' => 'general' ),
			'fa fa-calendar'               => array( 'label' => 'Calendar', 'group' => 'general' ),
			'fa fa-calendar-check-o'       => array( 'label' => 'Calendar Check O', 'group' => 'general' ),
			'fa fa-calendar-minus-o'       => array( 'label' => 'Calendar Minus O', 'group' => 'general' ),
			'fa fa-calendar-o'             => array( 'label' => 'Calendar O', 'group' => 'general' ),
			'fa fa-calendar-plus-o'        => array( 'label' => 'Calendar Plus O', 'group' => 'general' ),
			'fa fa-calendar-times-o'       => array( 'label' => 'Calendar Times O', 'group' => 'general' ),
			'fa fa-camera'                 => array( 'label' => 'Camera', 'group' => 'general' ),
			'fa fa-camera-retro'           => array( 'label' => 'Camera Retro', 'group' => 'general' ),
			'fa fa-car'                    => array( 'label' => 'Car', 'group' => 'general' ),
			'fa fa-caret-down'             => array( 'label' => 'Caret Down', 'group' => 'general' ),
			'fa fa-caret-left'             => array( 'label' => 'Caret Left', 'group' => 'general' ),
			'fa fa-caret-right'            => array( 'label' => 'Caret Right', 'group' => 'general' ),
			'fa fa-caret-square-o-down'    => array( 'label' => 'Caret Square O Down', 'group' => 'general' ),
			'fa fa-caret-square-o-left'    => array( 'label' => 'Caret Square O Left', 'group' => 'general' ),
			'fa fa-caret-square-o-right'   => array( 'label' => 'Caret Square O Right', 'group' => 'general' ),
			'fa fa-caret-square-o-up'      => array( 'label' => 'Caret Square O Up', 'group' => 'general' ),
			'fa fa-caret-up'               => array( 'label' => 'Caret Up', 'group' => 'general' ),
			'fa fa-cart-arrow-down'        => array( 'label' => 'Cart Arrow Down', 'group' => 'general' ),
			'fa fa-cart-plus'              => array( 'label' => 'Cart Plus', 'group' => 'general' ),
			'fa fa-cc'                     => array( 'label' => 'Cc', 'group' => 'general' ),
			'fa fa-cc-amex'                => array( 'label' => 'Cc Amex', 'group' => 'general' ),
			'fa fa-cc-diners-club'         => array( 'label' => 'Cc Diners Club', 'group' => 'general' ),
			'fa fa-cc-discover'            => array( 'label' => 'Cc Discover', 'group' => 'general' ),
			'fa fa-cc-jcb'                 => array( 'label' => 'Cc Jcb', 'group' => 'general' ),
			'fa fa-cc-mastercard'          => array( 'label' => 'Cc Mastercard', 'group' => 'general' ),
			'fa fa-cc-paypal'              => array( 'label' => 'Cc Paypal', 'group' => 'general' ),
			'fa fa-cc-stripe'              => array( 'label' => 'Cc Stripe', 'group' => 'general' ),
			'fa fa-cc-visa'                => array( 'label' => 'Cc Visa', 'group' => 'general' ),
			'fa fa-certificate'            => array( 'label' => 'Certificate', 'group' => 'general' ),
			'fa fa-chain'                  => array( 'label' => 'Chain', 'group' => 'general' ),
			'fa fa-chain-broken'           => array( 'label' => 'Chain Broken', 'group' => 'general' ),
			'fa fa-check'                  => array( 'label' => 'Check', 'group' => 'general' ),
			'fa fa-check-circle'           => array( 'label' => 'Check Circle', 'group' => 'general' ),
			'fa fa-check-circle-o'         => array( 'label' => 'Check Circle O', 'group' => 'general' ),
			'fa fa-check-square'           => array( 'label' => 'Check Square', 'group' => 'general' ),
			'fa fa-check-square-o'         => array( 'label' => 'Check Square O', 'group' => 'general' ),
			'fa fa-chevron-circle-down'    => array( 'label' => 'Chevron Circle Down', 'group' => 'general' ),
			'fa fa-chevron-circle-left'    => array( 'label' => 'Chevron Circle Left', 'group' => 'general' ),
			'fa fa-chevron-circle-right'   => array( 'label' => 'Chevron Circle Right', 'group' => 'general' ),
			'fa fa-chevron-circle-up'      => array( 'label' => 'Chevron Circle Up', 'group' => 'general' ),
			'fa fa-chevron-down'           => array( 'label' => 'Chevron Down', 'group' => 'general' ),
			'fa fa-chevron-left'           => array( 'label' => 'Chevron Left', 'group' => 'general' ),
			'fa fa-chevron-right'          => array( 'label' => 'Chevron Right', 'group' => 'general' ),
			'fa fa-chevron-up'             => array( 'label' => 'Chevron Up', 'group' => 'general' ),
			'fa fa-child'                  => array( 'label' => 'Child', 'group' => 'general' ),
			'fa fa-chrome'                 => array( 'label' => 'Chrome', 'group' => 'general' ),
			'fa fa-circle'                 => array( 'label' => 'Circle', 'group' => 'general' ),
			'fa fa-circle-o'               => array( 'label' => 'Circle O', 'group' => 'general' ),
			'fa fa-circle-o-notch'         => array( 'label' => 'Circle O Notch', 'group' => 'general' ),
			'fa fa-circle-thin'            => array( 'label' => 'Circle Thin', 'group' => 'general' ),
			'fa fa-clipboard'              => array( 'label' => 'Clipboard', 'group' => 'general' ),
			'fa fa-clock-o'                => array( 'label' => 'Clock O', 'group' => 'general' ),
			'fa fa-clone'                  => array( 'label' => 'Clone', 'group' => 'general' ),
			'fa fa-close'                  => array( 'label' => 'Close', 'group' => 'general' ),
			'fa fa-cloud'                  => array( 'label' => 'Cloud', 'group' => 'general' ),
			'fa fa-cloud-download'         => array( 'label' => 'Cloud Download', 'group' => 'general' ),
			'fa fa-cloud-upload'           => array( 'label' => 'Cloud Upload', 'group' => 'general' ),
			'fa fa-cny'                    => array( 'label' => 'Cny', 'group' => 'general' ),
			'fa fa-code'                   => array( 'label' => 'Code', 'group' => 'general' ),
			'fa fa-code-fork'              => array( 'label' => 'Code Fork', 'group' => 'general' ),
			'fa fa-codepen'                => array( 'label' => 'Codepen', 'group' => 'general' ),
			'fa fa-codiepie'               => array( 'label' => 'Codiepie', 'group' => 'general' ),
			'fa fa-coffee'                 => array( 'label' => 'Coffee', 'group' => 'general' ),
			'fa fa-cog'                    => array( 'label' => 'Cog', 'group' => 'general' ),
			'fa fa-cogs'                   => array( 'label' => 'Cogs', 'group' => 'general' ),
			'fa fa-columns'                => array( 'label' => 'Columns', 'group' => 'general' ),
			'fa fa-comment'                => array( 'label' => 'Comment', 'group' => 'general' ),
			'fa fa-comment-o'              => array( 'label' => 'Comment O', 'group' => 'general' ),
			'fa fa-commenting'             => array( 'label' => 'Commenting', 'group' => 'general' ),
			'fa fa-commenting-o'           => array( 'label' => 'Commenting O', 'group' => 'general' ),
			'fa fa-comments'               => array( 'label' => 'Comments', 'group' => 'general' ),
			'fa fa-comments-o'             => array( 'label' => 'Comments O', 'group' => 'general' ),
			'fa fa-compass'                => array( 'label' => 'Compass', 'group' => 'general' ),
			'fa fa-compress'               => array( 'label' => 'Compress', 'group' => 'general' ),
			'fa fa-connectdevelop'         => array( 'label' => 'Connectdevelop', 'group' => 'general' ),
			'fa fa-contao'                 => array( 'label' => 'Contao', 'group' => 'general' ),
			'fa fa-copy'                   => array( 'label' => 'Copy', 'group' => 'general' ),
			'fa fa-copyright'              => array( 'label' => 'Copyright', 'group' => 'general' ),
			'fa fa-creative-commons'       => array( 'label' => 'Creative Commons', 'group' => 'general' ),
			'fa fa-credit-card'            => array( 'label' => 'Credit Card', 'group' => 'general' ),
			'fa fa-credit-card-alt'        => array( 'label' => 'Credit Card Alt', 'group' => 'general' ),
			'fa fa-crop'                   => array( 'label' => 'Crop', 'group' => 'general' ),
			'fa fa-crosshairs'             => array( 'label' => 'Crosshairs', 'group' => 'general' ),
			'fa fa-css3'                   => array( 'label' => 'Css3', 'group' => 'general' ),
			'fa fa-cube'                   => array( 'label' => 'Cube', 'group' => 'general' ),
			'fa fa-cubes'                  => array( 'label' => 'Cubes', 'group' => 'general' ),
			'fa fa-cut'                    => array( 'label' => 'Cut', 'group' => 'general' ),
			'fa fa-cutlery'                => array( 'label' => 'Cutlery', 'group' => 'general' ),
			'fa fa-dashboard'              => array( 'label' => 'Dashboard', 'group' => 'general' ),
			'fa fa-dashcube'               => array( 'label' => 'Dashcube', 'group' => 'general' ),
			'fa fa-database'               => array( 'label' => 'Database', 'group' => 'general' ),
			'fa fa-dedent'                 => array( 'label' => 'Dedent', 'group' => 'general' ),
			'fa fa-delicious'              => array( 'label' => 'Delicious', 'group' => 'general' ),
			'fa fa-desktop'                => array( 'label' => 'Desktop', 'group' => 'general' ),
			'fa fa-deviantart'             => array( 'label' => 'Deviantart', 'group' => 'general' ),
			'fa fa-diamond'                => array( 'label' => 'Diamond', 'group' => 'general' ),
			'fa fa-digg'                   => array( 'label' => 'Digg', 'group' => 'general' ),
			'fa fa-dollar'                 => array( 'label' => 'Dollar', 'group' => 'general' ),
			'fa fa-dot-circle-o'           => array( 'label' => 'Dot Circle O', 'group' => 'general' ),
			'fa fa-download'               => array( 'label' => 'Download', 'group' => 'general' ),
			'fa fa-dribbble'               => array( 'label' => 'Dribbble', 'group' => 'general' ),
			'fa fa-dropbox'                => array( 'label' => 'Dropbox', 'group' => 'general' ),
			'fa fa-drupal'                 => array( 'label' => 'Drupal', 'group' => 'general' ),
			'fa fa-edge'                   => array( 'label' => 'Edge', 'group' => 'general' ),
			'fa fa-edit'                   => array( 'label' => 'Edit', 'group' => 'general' ),
			'fa fa-eject'                  => array( 'label' => 'Eject', 'group' => 'general' ),
			'fa fa-ellipsis-h'             => array( 'label' => 'Ellipsis H', 'group' => 'general' ),
			'fa fa-ellipsis-v'             => array( 'label' => 'Ellipsis V', 'group' => 'general' ),
			'fa fa-empire'                 => array( 'label' => 'Empire', 'group' => 'general' ),
			'fa fa-envelope'               => array( 'label' => 'Envelope', 'group' => 'general' ),
			'fa fa-envelope-o'             => array( 'label' => 'Envelope O', 'group' => 'general' ),
			'fa fa-envelope-square'        => array( 'label' => 'Envelope Square', 'group' => 'general' ),
			'fa fa-eraser'                 => array( 'label' => 'Eraser', 'group' => 'general' ),
			'fa fa-eur'                    => array( 'label' => 'Eur', 'group' => 'general' ),
			'fa fa-euro'                   => array( 'label' => 'Euro', 'group' => 'general' ),
			'fa fa-exchange'               => array( 'label' => 'Exchange', 'group' => 'general' ),
			'fa fa-exclamation'            => array( 'label' => 'Exclamation', 'group' => 'general' ),
			'fa fa-exclamation-circle'     => array( 'label' => 'Exclamation Circle', 'group' => 'general' ),
			'fa fa-exclamation-triangle'   => array( 'label' => 'Exclamation Triangle', 'group' => 'general' ),
			'fa fa-expand'                 => array( 'label' => 'Expand', 'group' => 'general' ),
			'fa fa-expeditedssl'           => array( 'label' => 'Expeditedssl', 'group' => 'general' ),
			'fa fa-external-link'          => array( 'label' => 'External Link', 'group' => 'general' ),
			'fa fa-external-link-square'   => array( 'label' => 'External Link Square', 'group' => 'general' ),
			'fa fa-eye'                    => array( 'label' => 'Eye', 'group' => 'general' ),
			'fa fa-eye-slash'              => array( 'label' => 'Eye Slash', 'group' => 'general' ),
			'fa fa-eyedropper'             => array( 'label' => 'Eyedropper', 'group' => 'general' ),
			'fa fa-facebook'               => array( 'label' => 'Facebook', 'group' => 'general' ),
			'fa fa-facebook-f'             => array( 'label' => 'Facebook F', 'group' => 'general' ),
			'fa fa-facebook-official'      => array( 'label' => 'Facebook Official', 'group' => 'general' ),
			'fa fa-facebook-square'        => array( 'label' => 'Facebook Square', 'group' => 'general' ),
			'fa fa-fast-backward'          => array( 'label' => 'Fast Backward', 'group' => 'general' ),
			'fa fa-fast-forward'           => array( 'label' => 'Fast Forward', 'group' => 'general' ),
			'fa fa-fax'                    => array( 'label' => 'Fax', 'group' => 'general' ),
			'fa fa-feed'                   => array( 'label' => 'Feed', 'group' => 'general' ),
			'fa fa-female'                 => array( 'label' => 'Female', 'group' => 'general' ),
			'fa fa-fighter-jet'            => array( 'label' => 'Fighter Jet', 'group' => 'general' ),
			'fa fa-file'                   => array( 'label' => 'File', 'group' => 'general' ),
			'fa fa-file-archive-o'         => array( 'label' => 'File Archive O', 'group' => 'general' ),
			'fa fa-file-audio-o'           => array( 'label' => 'File Audio O', 'group' => 'general' ),
			'fa fa-file-code-o'            => array( 'label' => 'File Code O', 'group' => 'general' ),
			'fa fa-file-excel-o'           => array( 'label' => 'File Excel O', 'group' => 'general' ),
			'fa fa-file-image-o'           => array( 'label' => 'File Image O', 'group' => 'general' ),
			'fa fa-file-movie-o'           => array( 'label' => 'File Movie O', 'group' => 'general' ),
			'fa fa-file-o'                 => array( 'label' => 'File O', 'group' => 'general' ),
			'fa fa-file-pdf-o'             => array( 'label' => 'File Pdf O', 'group' => 'general' ),
			'fa fa-file-photo-o'           => array( 'label' => 'File Photo O', 'group' => 'general' ),
			'fa fa-file-picture-o'         => array( 'label' => 'File Picture O', 'group' => 'general' ),
			'fa fa-file-powerpoint-o'      => array( 'label' => 'File Powerpoint O', 'group' => 'general' ),
			'fa fa-file-sound-o'           => array( 'label' => 'File Sound O', 'group' => 'general' ),
			'fa fa-file-text'              => array( 'label' => 'File Text', 'group' => 'general' ),
			'fa fa-file-text-o'            => array( 'label' => 'File Text O', 'group' => 'general' ),
			'fa fa-file-video-o'           => array( 'label' => 'File Video O', 'group' => 'general' ),
			'fa fa-file-word-o'            => array( 'label' => 'File Word O', 'group' => 'general' ),
			'fa fa-file-zip-o'             => array( 'label' => 'File Zip O', 'group' => 'general' ),
			'fa fa-files-o'                => array( 'label' => 'Files O', 'group' => 'general' ),
			'fa fa-film'                   => array( 'label' => 'Film', 'group' => 'general' ),
			'fa fa-filter'                 => array( 'label' => 'Filter', 'group' => 'general' ),
			'fa fa-fire'                   => array( 'label' => 'Fire', 'group' => 'general' ),
			'fa fa-fire-extinguisher'      => array( 'label' => 'Fire Extinguisher', 'group' => 'general' ),
			'fa fa-firefox'                => array( 'label' => 'Firefox', 'group' => 'general' ),
			'fa fa-flag'                   => array( 'label' => 'Flag', 'group' => 'general' ),
			'fa fa-flag-checkered'         => array( 'label' => 'Flag Checkered', 'group' => 'general' ),
			'fa fa-flag-o'                 => array( 'label' => 'Flag O', 'group' => 'general' ),
			'fa fa-flash'                  => array( 'label' => 'Flash', 'group' => 'general' ),
			'fa fa-flask'                  => array( 'label' => 'Flask', 'group' => 'general' ),
			'fa fa-flickr'                 => array( 'label' => 'Flickr', 'group' => 'general' ),
			'fa fa-floppy-o'               => array( 'label' => 'Floppy O', 'group' => 'general' ),
			'fa fa-folder'                 => array( 'label' => 'Folder', 'group' => 'general' ),
			'fa fa-folder-o'               => array( 'label' => 'Folder O', 'group' => 'general' ),
			'fa fa-folder-open'            => array( 'label' => 'Folder Open', 'group' => 'general' ),
			'fa fa-folder-open-o'          => array( 'label' => 'Folder Open O', 'group' => 'general' ),
			'fa fa-font'                   => array( 'label' => 'Font', 'group' => 'general' ),
			'fa fa-fonticons'              => array( 'label' => 'Fonticons', 'group' => 'general' ),
			'fa fa-fort-awesome'           => array( 'label' => 'Fort Awesome', 'group' => 'general' ),
			'fa fa-forumbee'               => array( 'label' => 'Forumbee', 'group' => 'general' ),
			'fa fa-forward'                => array( 'label' => 'Forward', 'group' => 'general' ),
			'fa fa-foursquare'             => array( 'label' => 'Foursquare', 'group' => 'general' ),
			'fa fa-frown-o'                => array( 'label' => 'Frown O', 'group' => 'general' ),
			'fa fa-futbol-o'               => array( 'label' => 'Futbol O', 'group' => 'general' ),
			'fa fa-gamepad'                => array( 'label' => 'Gamepad', 'group' => 'general' ),
			'fa fa-gavel'                  => array( 'label' => 'Gavel', 'group' => 'general' ),
			'fa fa-gbp'                    => array( 'label' => 'Gbp', 'group' => 'general' ),
			'fa fa-ge'                     => array( 'label' => 'Ge', 'group' => 'general' ),
			'fa fa-gear'                   => array( 'label' => 'Gear', 'group' => 'general' ),
			'fa fa-gears'                  => array( 'label' => 'Gears', 'group' => 'general' ),
			'fa fa-genderless'             => array( 'label' => 'Genderless', 'group' => 'general' ),
			'fa fa-get-pocket'             => array( 'label' => 'Get Pocket', 'group' => 'general' ),
			'fa fa-gg'                     => array( 'label' => 'Gg', 'group' => 'general' ),
			'fa fa-gg-circle'              => array( 'label' => 'Gg Circle', 'group' => 'general' ),
			'fa fa-gift'                   => array( 'label' => 'Gift', 'group' => 'general' ),
			'fa fa-git'                    => array( 'label' => 'Git', 'group' => 'general' ),
			'fa fa-git-square'             => array( 'label' => 'Git Square', 'group' => 'general' ),
			'fa fa-github'                 => array( 'label' => 'Github', 'group' => 'general' ),
			'fa fa-github-alt'             => array( 'label' => 'Github Alt', 'group' => 'general' ),
			'fa fa-github-square'          => array( 'label' => 'Github Square', 'group' => 'general' ),
			'fa fa-gittip'                 => array( 'label' => 'Gittip', 'group' => 'general' ),
			'fa fa-glass'                  => array( 'label' => 'Glass', 'group' => 'general' ),
			'fa fa-globe'                  => array( 'label' => 'Globe', 'group' => 'general' ),
			'fa fa-google'                 => array( 'label' => 'Google', 'group' => 'general' ),
			'fa fa-google-plus'            => array( 'label' => 'Google Plus', 'group' => 'general' ),
			'fa fa-google-plus-square'     => array( 'label' => 'Google Plus Square', 'group' => 'general' ),
			'fa fa-google-wallet'          => array( 'label' => 'Google Wallet', 'group' => 'general' ),
			'fa fa-graduation-cap'         => array( 'label' => 'Graduation Cap', 'group' => 'general' ),
			'fa fa-gratipay'               => array( 'label' => 'Gratipay', 'group' => 'general' ),
			'fa fa-group'                  => array( 'label' => 'Group', 'group' => 'general' ),
			'fa fa-h-square'               => array( 'label' => 'H Square', 'group' => 'general' ),
			'fa fa-hacker-news'            => array( 'label' => 'Hacker News', 'group' => 'general' ),
			'fa fa-hand-grab-o'            => array( 'label' => 'Hand Grab O', 'group' => 'general' ),
			'fa fa-hand-lizard-o'          => array( 'label' => 'Hand Lizard O', 'group' => 'general' ),
			'fa fa-hand-o-down'            => array( 'label' => 'Hand O Down', 'group' => 'general' ),
			'fa fa-hand-o-left'            => array( 'label' => 'Hand O Left', 'group' => 'general' ),
			'fa fa-hand-o-right'           => array( 'label' => 'Hand O Right', 'group' => 'general' ),
			'fa fa-hand-o-up'              => array( 'label' => 'Hand O Up', 'group' => 'general' ),
			'fa fa-hand-paper-o'           => array( 'label' => 'Hand Paper O', 'group' => 'general' ),
			'fa fa-hand-peace-o'           => array( 'label' => 'Hand Peace O', 'group' => 'general' ),
			'fa fa-hand-pointer-o'         => array( 'label' => 'Hand Pointer O', 'group' => 'general' ),
			'fa fa-hand-rock-o'            => array( 'label' => 'Hand Rock O', 'group' => 'general' ),
			'fa fa-hand-scissors-o'        => array( 'label' => 'Hand Scissors O', 'group' => 'general' ),
			'fa fa-hand-spock-o'           => array( 'label' => 'Hand Spock O', 'group' => 'general' ),
			'fa fa-hand-stop-o'            => array( 'label' => 'Hand Stop O', 'group' => 'general' ),
			'fa fa-hashtag'                => array( 'label' => 'Hashtag', 'group' => 'general' ),
			'fa fa-hdd-o'                  => array( 'label' => 'Hdd O', 'group' => 'general' ),
			'fa fa-header'                 => array( 'label' => 'Header', 'group' => 'general' ),
			'fa fa-headphones'             => array( 'label' => 'Headphones', 'group' => 'general' ),
			'fa fa-heart'                  => array( 'label' => 'Heart', 'group' => 'general' ),
			'fa fa-heart-o'                => array( 'label' => 'Heart O', 'group' => 'general' ),
			'fa fa-heartbeat'              => array( 'label' => 'Heartbeat', 'group' => 'general' ),
			'fa fa-history'                => array( 'label' => 'History', 'group' => 'general' ),
			'fa fa-home'                   => array( 'label' => 'Home', 'group' => 'general' ),
			'fa fa-hospital-o'             => array( 'label' => 'Hospital O', 'group' => 'general' ),
			'fa fa-hotel'                  => array( 'label' => 'Hotel', 'group' => 'general' ),
			'fa fa-hourglass'              => array( 'label' => 'Hourglass', 'group' => 'general' ),
			'fa fa-hourglass-1'            => array( 'label' => 'Hourglass 1', 'group' => 'general' ),
			'fa fa-hourglass-2'            => array( 'label' => 'Hourglass 2', 'group' => 'general' ),
			'fa fa-hourglass-3'            => array( 'label' => 'Hourglass 3', 'group' => 'general' ),
			'fa fa-hourglass-end'          => array( 'label' => 'Hourglass End', 'group' => 'general' ),
			'fa fa-hourglass-half'         => array( 'label' => 'Hourglass Half', 'group' => 'general' ),
			'fa fa-hourglass-o'            => array( 'label' => 'Hourglass O', 'group' => 'general' ),
			'fa fa-hourglass-start'        => array( 'label' => 'Hourglass Start', 'group' => 'general' ),
			'fa fa-houzz'                  => array( 'label' => 'Houzz', 'group' => 'general' ),
			'fa fa-html5'                  => array( 'label' => 'Html5', 'group' => 'general' ),
			'fa fa-i-cursor'               => array( 'label' => 'I Cursor', 'group' => 'general' ),
			'fa fa-ils'                    => array( 'label' => 'Ils', 'group' => 'general' ),
			'fa fa-image'                  => array( 'label' => 'Image', 'group' => 'general' ),
			'fa fa-inbox'                  => array( 'label' => 'Inbox', 'group' => 'general' ),
			'fa fa-indent'                 => array( 'label' => 'Indent', 'group' => 'general' ),
			'fa fa-industry'               => array( 'label' => 'Industry', 'group' => 'general' ),
			'fa fa-info'                   => array( 'label' => 'Info', 'group' => 'general' ),
			'fa fa-info-circle'            => array( 'label' => 'Info Circle', 'group' => 'general' ),
			'fa fa-inr'                    => array( 'label' => 'Inr', 'group' => 'general' ),
			'fa fa-instagram'              => array( 'label' => 'Instagram', 'group' => 'general' ),
			'fa fa-institution'            => array( 'label' => 'Institution', 'group' => 'general' ),
			'fa fa-internet-explorer'      => array( 'label' => 'Internet Explorer', 'group' => 'general' ),
			'fa fa-intersex'               => array( 'label' => 'Intersex', 'group' => 'general' ),
			'fa fa-ioxhost'                => array( 'label' => 'Ioxhost', 'group' => 'general' ),
			'fa fa-italic'                 => array( 'label' => 'Italic', 'group' => 'general' ),
			'fa fa-joomla'                 => array( 'label' => 'Joomla', 'group' => 'general' ),
			'fa fa-jpy'                    => array( 'label' => 'Jpy', 'group' => 'general' ),
			'fa fa-jsfiddle'               => array( 'label' => 'Jsfiddle', 'group' => 'general' ),
			'fa fa-key'                    => array( 'label' => 'Key', 'group' => 'general' ),
			'fa fa-keyboard-o'             => array( 'label' => 'Keyboard O', 'group' => 'general' ),
			'fa fa-krw'                    => array( 'label' => 'Krw', 'group' => 'general' ),
			'fa fa-language'               => array( 'label' => 'Language', 'group' => 'general' ),
			'fa fa-laptop'                 => array( 'label' => 'Laptop', 'group' => 'general' ),
			'fa fa-lastfm'                 => array( 'label' => 'Lastfm', 'group' => 'general' ),
			'fa fa-lastfm-square'          => array( 'label' => 'Lastfm Square', 'group' => 'general' ),
			'fa fa-leaf'                   => array( 'label' => 'Leaf', 'group' => 'general' ),
			'fa fa-leanpub'                => array( 'label' => 'Leanpub', 'group' => 'general' ),
			'fa fa-legal'                  => array( 'label' => 'Legal', 'group' => 'general' ),
			'fa fa-lemon-o'                => array( 'label' => 'Lemon O', 'group' => 'general' ),
			'fa fa-level-down'             => array( 'label' => 'Level Down', 'group' => 'general' ),
			'fa fa-level-up'               => array( 'label' => 'Level Up', 'group' => 'general' ),
			'fa fa-life-bouy'              => array( 'label' => 'Life Bouy', 'group' => 'general' ),
			'fa fa-life-buoy'              => array( 'label' => 'Life Buoy', 'group' => 'general' ),
			'fa fa-life-ring'              => array( 'label' => 'Life Ring', 'group' => 'general' ),
			'fa fa-life-saver'             => array( 'label' => 'Life Saver', 'group' => 'general' ),
			'fa fa-lightbulb-o'            => array( 'label' => 'Lightbulb O', 'group' => 'general' ),
			'fa fa-line-chart'             => array( 'label' => 'Line Chart', 'group' => 'general' ),
			'fa fa-link'                   => array( 'label' => 'Link', 'group' => 'general' ),
			'fa fa-linkedin'               => array( 'label' => 'Linkedin', 'group' => 'general' ),
			'fa fa-linkedin-square'        => array( 'label' => 'Linkedin Square', 'group' => 'general' ),
			'fa fa-linux'                  => array( 'label' => 'Linux', 'group' => 'general' ),
			'fa fa-list'                   => array( 'label' => 'List', 'group' => 'general' ),
			'fa fa-list-alt'               => array( 'label' => 'List Alt', 'group' => 'general' ),
			'fa fa-list-ol'                => array( 'label' => 'List Ol', 'group' => 'general' ),
			'fa fa-list-ul'                => array( 'label' => 'List Ul', 'group' => 'general' ),
			'fa fa-location-arrow'         => array( 'label' => 'Location Arrow', 'group' => 'general' ),
			'fa fa-lock'                   => array( 'label' => 'Lock', 'group' => 'general' ),
			'fa fa-long-arrow-down'        => array( 'label' => 'Long Arrow Down', 'group' => 'general' ),
			'fa fa-long-arrow-left'        => array( 'label' => 'Long Arrow Left', 'group' => 'general' ),
			'fa fa-long-arrow-right'       => array( 'label' => 'Long Arrow Right', 'group' => 'general' ),
			'fa fa-long-arrow-up'          => array( 'label' => 'Long Arrow Up', 'group' => 'general' ),
			'fa fa-magic'                  => array( 'label' => 'Magic', 'group' => 'general' ),
			'fa fa-magnet'                 => array( 'label' => 'Magnet', 'group' => 'general' ),
			'fa fa-mail-forward'           => array( 'label' => 'Mail Forward', 'group' => 'general' ),
			'fa fa-mail-reply'             => array( 'label' => 'Mail Reply', 'group' => 'general' ),
			'fa fa-mail-reply-all'         => array( 'label' => 'Mail Reply All', 'group' => 'general' ),
			'fa fa-male'                   => array( 'label' => 'Male', 'group' => 'general' ),
			'fa fa-map'                    => array( 'label' => 'Map', 'group' => 'general' ),
			'fa fa-map-marker'             => array( 'label' => 'Map Marker', 'group' => 'general' ),
			'fa fa-map-o'                  => array( 'label' => 'Map O', 'group' => 'general' ),
			'fa fa-map-pin'                => array( 'label' => 'Map Pin', 'group' => 'general' ),
			'fa fa-map-signs'              => array( 'label' => 'Map Signs', 'group' => 'general' ),
			'fa fa-mars'                   => array( 'label' => 'Mars', 'group' => 'general' ),
			'fa fa-mars-double'            => array( 'label' => 'Mars Double', 'group' => 'general' ),
			'fa fa-mars-stroke'            => array( 'label' => 'Mars Stroke', 'group' => 'general' ),
			'fa fa-mars-stroke-h'          => array( 'label' => 'Mars Stroke H', 'group' => 'general' ),
			'fa fa-mars-stroke-v'          => array( 'label' => 'Mars Stroke V', 'group' => 'general' ),
			'fa fa-maxcdn'                 => array( 'label' => 'Maxcdn', 'group' => 'general' ),
			'fa fa-meanpath'               => array( 'label' => 'Meanpath', 'group' => 'general' ),
			'fa fa-medium'                 => array( 'label' => 'Medium', 'group' => 'general' ),
			'fa fa-medkit'                 => array( 'label' => 'Medkit', 'group' => 'general' ),
			'fa fa-meh-o'                  => array( 'label' => 'Meh O', 'group' => 'general' ),
			'fa fa-mercury'                => array( 'label' => 'Mercury', 'group' => 'general' ),
			'fa fa-microphone'             => array( 'label' => 'Microphone', 'group' => 'general' ),
			'fa fa-microphone-slash'       => array( 'label' => 'Microphone Slash', 'group' => 'general' ),
			'fa fa-minus'                  => array( 'label' => 'Minus', 'group' => 'general' ),
			'fa fa-minus-circle'           => array( 'label' => 'Minus Circle', 'group' => 'general' ),
			'fa fa-minus-square'           => array( 'label' => 'Minus Square', 'group' => 'general' ),
			'fa fa-minus-square-o'         => array( 'label' => 'Minus Square O', 'group' => 'general' ),
			'fa fa-mixcloud'               => array( 'label' => 'Mixcloud', 'group' => 'general' ),
			'fa fa-mobile'                 => array( 'label' => 'Mobile', 'group' => 'general' ),
			'fa fa-mobile-phone'           => array( 'label' => 'Mobile Phone', 'group' => 'general' ),
			'fa fa-modx'                   => array( 'label' => 'Modx', 'group' => 'general' ),
			'fa fa-money'                  => array( 'label' => 'Money', 'group' => 'general' ),
			'fa fa-moon-o'                 => array( 'label' => 'Moon O', 'group' => 'general' ),
			'fa fa-mortar-board'           => array( 'label' => 'Mortar Board', 'group' => 'general' ),
			'fa fa-motorcycle'             => array( 'label' => 'Motorcycle', 'group' => 'general' ),
			'fa fa-mouse-pointer'          => array( 'label' => 'Mouse Pointer', 'group' => 'general' ),
			'fa fa-music'                  => array( 'label' => 'Music', 'group' => 'general' ),
			'fa fa-navicon'                => array( 'label' => 'Navicon', 'group' => 'general' ),
			'fa fa-neuter'                 => array( 'label' => 'Neuter', 'group' => 'general' ),
			'fa fa-newspaper-o'            => array( 'label' => 'Newspaper O', 'group' => 'general' ),
			'fa fa-object-group'           => array( 'label' => 'Object Group', 'group' => 'general' ),
			'fa fa-object-ungroup'         => array( 'label' => 'Object Ungroup', 'group' => 'general' ),
			'fa fa-odnoklassniki'          => array( 'label' => 'Odnoklassniki', 'group' => 'general' ),
			'fa fa-odnoklassniki-square'   => array( 'label' => 'Odnoklassniki Square', 'group' => 'general' ),
			'fa fa-opencart'               => array( 'label' => 'Opencart', 'group' => 'general' ),
			'fa fa-openid'                 => array( 'label' => 'Openid', 'group' => 'general' ),
			'fa fa-opera'                  => array( 'label' => 'Opera', 'group' => 'general' ),
			'fa fa-optin-monster'          => array( 'label' => 'Optin Monster', 'group' => 'general' ),
			'fa fa-outdent'                => array( 'label' => 'Outdent', 'group' => 'general' ),
			'fa fa-pagelines'              => array( 'label' => 'Pagelines', 'group' => 'general' ),
			'fa fa-paint-brush'            => array( 'label' => 'Paint Brush', 'group' => 'general' ),
			'fa fa-paper-plane'            => array( 'label' => 'Paper Plane', 'group' => 'general' ),
			'fa fa-paper-plane-o'          => array( 'label' => 'Paper Plane O', 'group' => 'general' ),
			'fa fa-paperclip'              => array( 'label' => 'Paperclip', 'group' => 'general' ),
			'fa fa-paragraph'              => array( 'label' => 'Paragraph', 'group' => 'general' ),
			'fa fa-paste'                  => array( 'label' => 'Paste', 'group' => 'general' ),
			'fa fa-pause'                  => array( 'label' => 'Pause', 'group' => 'general' ),
			'fa fa-pause-circle'           => array( 'label' => 'Pause Circle', 'group' => 'general' ),
			'fa fa-pause-circle-o'         => array( 'label' => 'Pause Circle O', 'group' => 'general' ),
			'fa fa-paw'                    => array( 'label' => 'Paw', 'group' => 'general' ),
			'fa fa-paypal'                 => array( 'label' => 'Paypal', 'group' => 'general' ),
			'fa fa-pencil'                 => array( 'label' => 'Pencil', 'group' => 'general' ),
			'fa fa-pencil-square'          => array( 'label' => 'Pencil Square', 'group' => 'general' ),
			'fa fa-pencil-square-o'        => array( 'label' => 'Pencil Square O', 'group' => 'general' ),
			'fa fa-percent'                => array( 'label' => 'Percent', 'group' => 'general' ),
			'fa fa-phone'                  => array( 'label' => 'Phone', 'group' => 'general' ),
			'fa fa-phone-square'           => array( 'label' => 'Phone Square', 'group' => 'general' ),
			'fa fa-photo'                  => array( 'label' => 'Photo', 'group' => 'general' ),
			'fa fa-picture-o'              => array( 'label' => 'Picture O', 'group' => 'general' ),
			'fa fa-pie-chart'              => array( 'label' => 'Pie Chart', 'group' => 'general' ),
			'fa fa-pied-piper'             => array( 'label' => 'Pied Piper', 'group' => 'general' ),
			'fa fa-pied-piper-alt'         => array( 'label' => 'Pied Piper Alt', 'group' => 'general' ),
			'fa fa-pinterest'              => array( 'label' => 'Pinterest', 'group' => 'general' ),
			'fa fa-pinterest-p'            => array( 'label' => 'Pinterest P', 'group' => 'general' ),
			'fa fa-pinterest-square'       => array( 'label' => 'Pinterest Square', 'group' => 'general' ),
			'fa fa-plane'                  => array( 'label' => 'Plane', 'group' => 'general' ),
			'fa fa-play'                   => array( 'label' => 'Play', 'group' => 'general' ),
			'fa fa-play-circle'            => array( 'label' => 'Play Circle', 'group' => 'general' ),
			'fa fa-play-circle-o'          => array( 'label' => 'Play Circle O', 'group' => 'general' ),
			'fa fa-plug'                   => array( 'label' => 'Plug', 'group' => 'general' ),
			'fa fa-plus'                   => array( 'label' => 'Plus', 'group' => 'general' ),
			'fa fa-plus-circle'            => array( 'label' => 'Plus Circle', 'group' => 'general' ),
			'fa fa-plus-square'            => array( 'label' => 'Plus Square', 'group' => 'general' ),
			'fa fa-plus-square-o'          => array( 'label' => 'Plus Square O', 'group' => 'general' ),
			'fa fa-power-off'              => array( 'label' => 'Power Off', 'group' => 'general' ),
			'fa fa-print'                  => array( 'label' => 'Print', 'group' => 'general' ),
			'fa fa-product-hunt'           => array( 'label' => 'Product Hunt', 'group' => 'general' ),
			'fa fa-puzzle-piece'           => array( 'label' => 'Puzzle Piece', 'group' => 'general' ),
			'fa fa-qq'                     => array( 'label' => 'Qq', 'group' => 'general' ),
			'fa fa-qrcode'                 => array( 'label' => 'Qrcode', 'group' => 'general' ),
			'fa fa-question'               => array( 'label' => 'Question', 'group' => 'general' ),
			'fa fa-question-circle'        => array( 'label' => 'Question Circle', 'group' => 'general' ),
			'fa fa-quote-left'             => array( 'label' => 'Quote Left', 'group' => 'general' ),
			'fa fa-quote-right'            => array( 'label' => 'Quote Right', 'group' => 'general' ),
			'fa fa-ra'                     => array( 'label' => 'Ra', 'group' => 'general' ),
			'fa fa-random'                 => array( 'label' => 'Random', 'group' => 'general' ),
			'fa fa-rebel'                  => array( 'label' => 'Rebel', 'group' => 'general' ),
			'fa fa-recycle'                => array( 'label' => 'Recycle', 'group' => 'general' ),
			'fa fa-reddit'                 => array( 'label' => 'Reddit', 'group' => 'general' ),
			'fa fa-reddit-alien'           => array( 'label' => 'Reddit Alien', 'group' => 'general' ),
			'fa fa-reddit-square'          => array( 'label' => 'Reddit Square', 'group' => 'general' ),
			'fa fa-refresh'                => array( 'label' => 'Refresh', 'group' => 'general' ),
			'fa fa-registered'             => array( 'label' => 'Registered', 'group' => 'general' ),
			'fa fa-remove'                 => array( 'label' => 'Remove', 'group' => 'general' ),
			'fa fa-renren'                 => array( 'label' => 'Renren', 'group' => 'general' ),
			'fa fa-reorder'                => array( 'label' => 'Reorder', 'group' => 'general' ),
			'fa fa-repeat'                 => array( 'label' => 'Repeat', 'group' => 'general' ),
			'fa fa-reply'                  => array( 'label' => 'Reply', 'group' => 'general' ),
			'fa fa-reply-all'              => array( 'label' => 'Reply All', 'group' => 'general' ),
			'fa fa-retweet'                => array( 'label' => 'Retweet', 'group' => 'general' ),
			'fa fa-rmb'                    => array( 'label' => 'Rmb', 'group' => 'general' ),
			'fa fa-road'                   => array( 'label' => 'Road', 'group' => 'general' ),
			'fa fa-rocket'                 => array( 'label' => 'Rocket', 'group' => 'general' ),
			'fa fa-rotate-left'            => array( 'label' => 'Rotate Left', 'group' => 'general' ),
			'fa fa-rotate-right'           => array( 'label' => 'Rotate Right', 'group' => 'general' ),
			'fa fa-rouble'                 => array( 'label' => 'Rouble', 'group' => 'general' ),
			'fa fa-rss'                    => array( 'label' => 'Rss', 'group' => 'general' ),
			'fa fa-rss-square'             => array( 'label' => 'Rss Square', 'group' => 'general' ),
			'fa fa-rub'                    => array( 'label' => 'Rub', 'group' => 'general' ),
			'fa fa-ruble'                  => array( 'label' => 'Ruble', 'group' => 'general' ),
			'fa fa-rupee'                  => array( 'label' => 'Rupee', 'group' => 'general' ),
			'fa fa-safari'                 => array( 'label' => 'Safari', 'group' => 'general' ),
			'fa fa-save'                   => array( 'label' => 'Save', 'group' => 'general' ),
			'fa fa-scissors'               => array( 'label' => 'Scissors', 'group' => 'general' ),
			'fa fa-scribd'                 => array( 'label' => 'Scribd', 'group' => 'general' ),
			'fa fa-search'                 => array( 'label' => 'Search', 'group' => 'general' ),
			'fa fa-search-minus'           => array( 'label' => 'Search Minus', 'group' => 'general' ),
			'fa fa-search-plus'            => array( 'label' => 'Search Plus', 'group' => 'general' ),
			'fa fa-sellsy'                 => array( 'label' => 'Sellsy', 'group' => 'general' ),
			'fa fa-send'                   => array( 'label' => 'Send', 'group' => 'general' ),
			'fa fa-send-o'                 => array( 'label' => 'Send O', 'group' => 'general' ),
			'fa fa-server'                 => array( 'label' => 'Server', 'group' => 'general' ),
			'fa fa-share'                  => array( 'label' => 'Share', 'group' => 'general' ),
			'fa fa-share-alt'              => array( 'label' => 'Share Alt', 'group' => 'general' ),
			'fa fa-share-alt-square'       => array( 'label' => 'Share Alt Square', 'group' => 'general' ),
			'fa fa-share-square'           => array( 'label' => 'Share Square', 'group' => 'general' ),
			'fa fa-share-square-o'         => array( 'label' => 'Share Square O', 'group' => 'general' ),
			'fa fa-shekel'                 => array( 'label' => 'Shekel', 'group' => 'general' ),
			'fa fa-sheqel'                 => array( 'label' => 'Sheqel', 'group' => 'general' ),
			'fa fa-shield'                 => array( 'label' => 'Shield', 'group' => 'general' ),
			'fa fa-ship'                   => array( 'label' => 'Ship', 'group' => 'general' ),
			'fa fa-shirtsinbulk'           => array( 'label' => 'Shirtsinbulk', 'group' => 'general' ),
			'fa fa-shopping-bag'           => array( 'label' => 'Shopping Bag', 'group' => 'general' ),
			'fa fa-shopping-basket'        => array( 'label' => 'Shopping Basket', 'group' => 'general' ),
			'fa fa-shopping-cart'          => array( 'label' => 'Shopping Cart', 'group' => 'general' ),
			'fa fa-sign-in'                => array( 'label' => 'Sign In', 'group' => 'general' ),
			'fa fa-sign-out'               => array( 'label' => 'Sign Out', 'group' => 'general' ),
			'fa fa-signal'                 => array( 'label' => 'Signal', 'group' => 'general' ),
			'fa fa-simplybuilt'            => array( 'label' => 'Simplybuilt', 'group' => 'general' ),
			'fa fa-sitemap'                => array( 'label' => 'Sitemap', 'group' => 'general' ),
			'fa fa-skyatlas'               => array( 'label' => 'Skyatlas', 'group' => 'general' ),
			'fa fa-skype'                  => array( 'label' => 'Skype', 'group' => 'general' ),
			'fa fa-slack'                  => array( 'label' => 'Slack', 'group' => 'general' ),
			'fa fa-sliders'                => array( 'label' => 'Sliders', 'group' => 'general' ),
			'fa fa-slideshare'             => array( 'label' => 'Slideshare', 'group' => 'general' ),
			'fa fa-smile-o'                => array( 'label' => 'Smile O', 'group' => 'general' ),
			'fa fa-soccer-ball-o'          => array( 'label' => 'Soccer Ball O', 'group' => 'general' ),
			'fa fa-sort'                   => array( 'label' => 'Sort', 'group' => 'general' ),
			'fa fa-sort-alpha-asc'         => array( 'label' => 'Sort Alpha Asc', 'group' => 'general' ),
			'fa fa-sort-alpha-desc'        => array( 'label' => 'Sort Alpha Desc', 'group' => 'general' ),
			'fa fa-sort-amount-asc'        => array( 'label' => 'Sort Amount Asc', 'group' => 'general' ),
			'fa fa-sort-amount-desc'       => array( 'label' => 'Sort Amount Desc', 'group' => 'general' ),
			'fa fa-sort-asc'               => array( 'label' => 'Sort Asc', 'group' => 'general' ),
			'fa fa-sort-desc'              => array( 'label' => 'Sort Desc', 'group' => 'general' ),
			'fa fa-sort-down'              => array( 'label' => 'Sort Down', 'group' => 'general' ),
			'fa fa-sort-numeric-asc'       => array( 'label' => 'Sort Numeric Asc', 'group' => 'general' ),
			'fa fa-sort-numeric-desc'      => array( 'label' => 'Sort Numeric Desc', 'group' => 'general' ),
			'fa fa-sort-up'                => array( 'label' => 'Sort Up', 'group' => 'general' ),
			'fa fa-soundcloud'             => array( 'label' => 'Soundcloud', 'group' => 'general' ),
			'fa fa-space-shuttle'          => array( 'label' => 'Space Shuttle', 'group' => 'general' ),
			'fa fa-spinner'                => array( 'label' => 'Spinner', 'group' => 'general' ),
			'fa fa-spoon'                  => array( 'label' => 'Spoon', 'group' => 'general' ),
			'fa fa-spotify'                => array( 'label' => 'Spotify', 'group' => 'general' ),
			'fa fa-square'                 => array( 'label' => 'Square', 'group' => 'general' ),
			'fa fa-square-o'               => array( 'label' => 'Square O', 'group' => 'general' ),
			'fa fa-stack-exchange'         => array( 'label' => 'Stack Exchange', 'group' => 'general' ),
			'fa fa-stack-overflow'         => array( 'label' => 'Stack Overflow', 'group' => 'general' ),
			'fa fa-star'                   => array( 'label' => 'Star', 'group' => 'general' ),
			'fa fa-star-half'              => array( 'label' => 'Star Half', 'group' => 'general' ),
			'fa fa-star-half-empty'        => array( 'label' => 'Star Half Empty', 'group' => 'general' ),
			'fa fa-star-half-full'         => array( 'label' => 'Star Half Full', 'group' => 'general' ),
			'fa fa-star-half-o'            => array( 'label' => 'Star Half O', 'group' => 'general' ),
			'fa fa-star-o'                 => array( 'label' => 'Star O', 'group' => 'general' ),
			'fa fa-steam'                  => array( 'label' => 'Steam', 'group' => 'general' ),
			'fa fa-steam-square'           => array( 'label' => 'Steam Square', 'group' => 'general' ),
			'fa fa-step-backward'          => array( 'label' => 'Step Backward', 'group' => 'general' ),
			'fa fa-step-forward'           => array( 'label' => 'Step Forward', 'group' => 'general' ),
			'fa fa-stethoscope'            => array( 'label' => 'Stethoscope', 'group' => 'general' ),
			'fa fa-sticky-note'            => array( 'label' => 'Sticky Note', 'group' => 'general' ),
			'fa fa-sticky-note-o'          => array( 'label' => 'Sticky Note O', 'group' => 'general' ),
			'fa fa-stop'                   => array( 'label' => 'Stop', 'group' => 'general' ),
			'fa fa-stop-circle'            => array( 'label' => 'Stop Circle', 'group' => 'general' ),
			'fa fa-stop-circle-o'          => array( 'label' => 'Stop Circle O', 'group' => 'general' ),
			'fa fa-street-view'            => array( 'label' => 'Street View', 'group' => 'general' ),
			'fa fa-strikethrough'          => array( 'label' => 'Strikethrough', 'group' => 'general' ),
			'fa fa-stumbleupon'            => array( 'label' => 'Stumbleupon', 'group' => 'general' ),
			'fa fa-stumbleupon-circle'     => array( 'label' => 'Stumbleupon Circle', 'group' => 'general' ),
			'fa fa-subscript'              => array( 'label' => 'Subscript', 'group' => 'general' ),
			'fa fa-subway'                 => array( 'label' => 'Subway', 'group' => 'general' ),
			'fa fa-suitcase'               => array( 'label' => 'Suitcase', 'group' => 'general' ),
			'fa fa-sun-o'                  => array( 'label' => 'Sun O', 'group' => 'general' ),
			'fa fa-superscript'            => array( 'label' => 'Superscript', 'group' => 'general' ),
			'fa fa-support'                => array( 'label' => 'Support', 'group' => 'general' ),
			'fa fa-table'                  => array( 'label' => 'Table', 'group' => 'general' ),
			'fa fa-tablet'                 => array( 'label' => 'Tablet', 'group' => 'general' ),
			'fa fa-tachometer'             => array( 'label' => 'Tachometer', 'group' => 'general' ),
			'fa fa-tag'                    => array( 'label' => 'Tag', 'group' => 'general' ),
			'fa fa-tags'                   => array( 'label' => 'Tags', 'group' => 'general' ),
			'fa fa-tasks'                  => array( 'label' => 'Tasks', 'group' => 'general' ),
			'fa fa-taxi'                   => array( 'label' => 'Taxi', 'group' => 'general' ),
			'fa fa-television'             => array( 'label' => 'Television', 'group' => 'general' ),
			'fa fa-tencent-weibo'          => array( 'label' => 'Tencent Weibo', 'group' => 'general' ),
			'fa fa-terminal'               => array( 'label' => 'Terminal', 'group' => 'general' ),
			'fa fa-text-height'            => array( 'label' => 'Text Height', 'group' => 'general' ),
			'fa fa-text-width'             => array( 'label' => 'Text Width', 'group' => 'general' ),
			'fa fa-th'                     => array( 'label' => 'Th', 'group' => 'general' ),
			'fa fa-th-large'               => array( 'label' => 'Th Large', 'group' => 'general' ),
			'fa fa-th-list'                => array( 'label' => 'Th List', 'group' => 'general' ),
			'fa fa-thumb-tack'             => array( 'label' => 'Thumb Tack', 'group' => 'general' ),
			'fa fa-thumbs-down'            => array( 'label' => 'Thumbs Down', 'group' => 'general' ),
			'fa fa-thumbs-o-down'          => array( 'label' => 'Thumbs O Down', 'group' => 'general' ),
			'fa fa-thumbs-o-up'            => array( 'label' => 'Thumbs O Up', 'group' => 'general' ),
			'fa fa-thumbs-up'              => array( 'label' => 'Thumbs Up', 'group' => 'general' ),
			'fa fa-ticket'                 => array( 'label' => 'Ticket', 'group' => 'general' ),
			'fa fa-times'                  => array( 'label' => 'Times', 'group' => 'general' ),
			'fa fa-times-circle'           => array( 'label' => 'Times Circle', 'group' => 'general' ),
			'fa fa-times-circle-o'         => array( 'label' => 'Times Circle O', 'group' => 'general' ),
			'fa fa-tint'                   => array( 'label' => 'Tint', 'group' => 'general' ),
			'fa fa-toggle-down'            => array( 'label' => 'Toggle Down', 'group' => 'general' ),
			'fa fa-toggle-left'            => array( 'label' => 'Toggle Left', 'group' => 'general' ),
			'fa fa-toggle-off'             => array( 'label' => 'Toggle Off', 'group' => 'general' ),
			'fa fa-toggle-on'              => array( 'label' => 'Toggle On', 'group' => 'general' ),
			'fa fa-toggle-right'           => array( 'label' => 'Toggle Right', 'group' => 'general' ),
			'fa fa-toggle-up'              => array( 'label' => 'Toggle Up', 'group' => 'general' ),
			'fa fa-trademark'              => array( 'label' => 'Trademark', 'group' => 'general' ),
			'fa fa-train'                  => array( 'label' => 'Train', 'group' => 'general' ),
			'fa fa-transgender'            => array( 'label' => 'Transgender', 'group' => 'general' ),
			'fa fa-transgender-alt'        => array( 'label' => 'Transgender Alt', 'group' => 'general' ),
			'fa fa-trash'                  => array( 'label' => 'Trash', 'group' => 'general' ),
			'fa fa-trash-o'                => array( 'label' => 'Trash O', 'group' => 'general' ),
			'fa fa-tree'                   => array( 'label' => 'Tree', 'group' => 'general' ),
			'fa fa-trello'                 => array( 'label' => 'Trello', 'group' => 'general' ),
			'fa fa-tripadvisor'            => array( 'label' => 'Tripadvisor', 'group' => 'general' ),
			'fa fa-trophy'                 => array( 'label' => 'Trophy', 'group' => 'general' ),
			'fa fa-truck'                  => array( 'label' => 'Truck', 'group' => 'general' ),
			'fa fa-try'                    => array( 'label' => 'Try', 'group' => 'general' ),
			'fa fa-tty'                    => array( 'label' => 'Tty', 'group' => 'general' ),
			'fa fa-tumblr'                 => array( 'label' => 'Tumblr', 'group' => 'general' ),
			'fa fa-tumblr-square'          => array( 'label' => 'Tumblr Square', 'group' => 'general' ),
			'fa fa-turkish-lira'           => array( 'label' => 'Turkish Lira', 'group' => 'general' ),
			'fa fa-tv'                     => array( 'label' => 'Tv', 'group' => 'general' ),
			'fa fa-twitch'                 => array( 'label' => 'Twitch', 'group' => 'general' ),
			'fa fa-twitter'                => array( 'label' => 'Twitter', 'group' => 'general' ),
			'fa fa-twitter-square'         => array( 'label' => 'Twitter Square', 'group' => 'general' ),
			'fa fa-umbrella'               => array( 'label' => 'Umbrella', 'group' => 'general' ),
			'fa fa-underline'              => array( 'label' => 'Underline', 'group' => 'general' ),
			'fa fa-undo'                   => array( 'label' => 'Undo', 'group' => 'general' ),
			'fa fa-university'             => array( 'label' => 'University', 'group' => 'general' ),
			'fa fa-unlink'                 => array( 'label' => 'Unlink', 'group' => 'general' ),
			'fa fa-unlock'                 => array( 'label' => 'Unlock', 'group' => 'general' ),
			'fa fa-unlock-alt'             => array( 'label' => 'Unlock Alt', 'group' => 'general' ),
			'fa fa-unsorted'               => array( 'label' => 'Unsorted', 'group' => 'general' ),
			'fa fa-upload'                 => array( 'label' => 'Upload', 'group' => 'general' ),
			'fa fa-usb'                    => array( 'label' => 'Usb', 'group' => 'general' ),
			'fa fa-usd'                    => array( 'label' => 'Usd', 'group' => 'general' ),
			'fa fa-user'                   => array( 'label' => 'User', 'group' => 'general' ),
			'fa fa-user-md'                => array( 'label' => 'User Md', 'group' => 'general' ),
			'fa fa-user-plus'              => array( 'label' => 'User Plus', 'group' => 'general' ),
			'fa fa-user-secret'            => array( 'label' => 'User Secret', 'group' => 'general' ),
			'fa fa-user-times'             => array( 'label' => 'User Times', 'group' => 'general' ),
			'fa fa-users'                  => array( 'label' => 'Users', 'group' => 'general' ),
			'fa fa-venus'                  => array( 'label' => 'Venus', 'group' => 'general' ),
			'fa fa-venus-double'           => array( 'label' => 'Venus Double', 'group' => 'general' ),
			'fa fa-venus-mars'             => array( 'label' => 'Venus Mars', 'group' => 'general' ),
			'fa fa-viacoin'                => array( 'label' => 'Viacoin', 'group' => 'general' ),
			'fa fa-video-camera'           => array( 'label' => 'Video Camera', 'group' => 'general' ),
			'fa fa-vimeo'                  => array( 'label' => 'Vimeo', 'group' => 'general' ),
			'fa fa-vimeo-square'           => array( 'label' => 'Vimeo Square', 'group' => 'general' ),
			'fa fa-vine'                   => array( 'label' => 'Vine', 'group' => 'general' ),
			'fa fa-vk'                     => array( 'label' => 'Vk', 'group' => 'general' ),
			'fa fa-volume-down'            => array( 'label' => 'Volume Down', 'group' => 'general' ),
			'fa fa-volume-off'             => array( 'label' => 'Volume Off', 'group' => 'general' ),
			'fa fa-volume-up'              => array( 'label' => 'Volume Up', 'group' => 'general' ),
			'fa fa-warning'                => array( 'label' => 'Warning', 'group' => 'general' ),
			'fa fa-wechat'                 => array( 'label' => 'Wechat', 'group' => 'general' ),
			'fa fa-weibo'                  => array( 'label' => 'Weibo', 'group' => 'general' ),
			'fa fa-weixin'                 => array( 'label' => 'Weixin', 'group' => 'general' ),
			'fa fa-whatsapp'               => array( 'label' => 'Whatsapp', 'group' => 'general' ),
			'fa fa-wheelchair'             => array( 'label' => 'Wheelchair', 'group' => 'general' ),
			'fa fa-wifi'                   => array( 'label' => 'Wifi', 'group' => 'general' ),
			'fa fa-wikipedia-w'            => array( 'label' => 'Wikipedia W', 'group' => 'general' ),
			'fa fa-windows'                => array( 'label' => 'Windows', 'group' => 'general' ),
			'fa fa-won'                    => array( 'label' => 'Won', 'group' => 'general' ),
			'fa fa-wordpress'              => array( 'label' => 'Wordpress', 'group' => 'general' ),
			'fa fa-wrench'                 => array( 'label' => 'Wrench', 'group' => 'general' ),
			'fa fa-xing'                   => array( 'label' => 'Xing', 'group' => 'general' ),
			'fa fa-xing-square'            => array( 'label' => 'Xing Square', 'group' => 'general' ),
			'fa fa-y-combinator'           => array( 'label' => 'Y Combinator', 'group' => 'general' ),
			'fa fa-y-combinator-square'    => array( 'label' => 'Y Combinator Square', 'group' => 'general' ),
			'fa fa-yahoo'                  => array( 'label' => 'Yahoo', 'group' => 'general' ),
			'fa fa-yc'                     => array( 'label' => 'Yc', 'group' => 'general' ),
			'fa fa-yc-square'              => array( 'label' => 'Yc Square', 'group' => 'general' ),
			'fa fa-yelp'                   => array( 'label' => 'Yelp', 'group' => 'general' ),
			'fa fa-yen'                    => array( 'label' => 'Yen', 'group' => 'general' ),
			'fa fa-youtube'                => array( 'label' => 'Youtube', 'group' => 'general' ),
			'fa fa-youtube-play'           => array( 'label' => 'Youtube Play', 'group' => 'general' ),
			'fa fa-youtube-square'         => array( 'label' => 'Youtube Square', 'group' => 'general' )
		) );
	}
}
